### ISSUE TITLE
Feature/Bug: Add tags.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/aws-lambda-serverless-reference#41]
Add tags to mirror TF.

Diff:

```diff
diff --git a/serverless.yml b/serverless.yml
index 7d34950..dbd122e 100644
--- a/serverless.yml
+++ b/serverless.yml
@@ -36,6 +36,7 @@ plugins:
 
 provider:
   name: aws
+
   # Required: import the default role that terraform-aws-serverless generates.
   role:
     Fn::ImportValue: tf-${self:custom.service}-${self:custom.stage}-LambdaExecutionRoleArn
@@ -44,14 +45,26 @@ provider:
     # IAM role in place of its autogenerated one. If you provide a custom role,
     # expose it as an export on a CloudFormation stack and import it like so:
     # Fn::ImportValue: tf-${self:custom.service}-${self:custom.stage}-LambdaExecutionRoleCustomArn
+
+  # Lambda configuration
   runtime: nodejs8.10
+  timeout: 30 # seconds (`300` max)
+  memorySize: 128 # MB value (`1024` default)
+
+  # Deployment / environment configuration
   region: ${self:custom.region}
   stage: ${self:custom.stage}
   environment:
     STAGE: ${self:custom.stage}
     SERVICE_NAME: ${self:custom.service}
-  timeout: 30 # seconds (`300` max)
-  memorySize: 128 # MB value (`1024` default)
+
+  # AWS Resource Tags: Match terraform module
+  stackTags: # For CF stack
+    Stage: ${self:custom.stage}
+    Service: ${self:custom.service}
+  tags: # For resources
+    Stage: ${self:custom.stage}
+    Service: ${self:custom.service}
 
 functions:
   # SCENARIO - base: The simplest, vanilla Serverless app.
```

But get error:

```
  Serverless Error ---------------------------------------
 
  User: arn:aws:iam::ACCOUNT:user/FIRST.LAST-admin is not authorized to perform: apigateway:PUT on resource: arn:aws:apigateway:us-east-1::/tags/arn%3Aaws%3Aapigateway%3Aus-east-1%3A%3A%2Frestapis%2Fvgrecx13z6%2Fstages%2Fsandbox
```

Also in SLS CF updates, finding messages like:

```
Failed to set tags on AWS::Lambda::Function. IAM permissions lambda:ListTags, lambda:TagResource and lambda:UntagResource are required to tag AWS::Lambda::Function resources and to propagate stack level tags.
```

Likely need additional permissions in: https://github.com/FormidableLabs/terraform-aws-serverless/blob/d370fd518dc9f86704bd3e3b597a18682f8930c8/policy-developer.tf#L124

(`local.sls_apigw_arn` doesn't cover `/tags/*`)

## Task
- [x] Fix tags for `terraform-aws-serverless`
- [x] Enable diff above.
- [x] Add tags for reference app TF resources (like VPCs, etc.)
